Add ansible docker certbot config
paralect/ansible-letsencrypt pull request #1
Opened 2018-08-20 18:52 UTC by ezhivitsa

@anorsich Please, review

2018-08-22 10:18 UTC, anorsich requested changes
I didn't test the role (hope you did :)). Things looking good, we only need to add some details to the documentation and this PR should be good to go :)

2018-08-22 10:18 UTC, anorsich commented on README.md
> +The ansible role for generating [letsecrypt](https://letsencrypt.org/) certificates.
I think we need to add more explanation here. We need to mention that (we need to add feature list with emotions, just like on other repos):
 - role can generate single certificates for specific domains/subdomains
 - role can generate wildcard certificates
 - I am not sure what this role do with DNS provider (Cloudflare for example) and why it need it, but we need to mention this as well :)
- we need to mention that certificates will automatically renew every month (or so)
- we need to mention where generated certificates stored and how their naming works.

2018-09-23 19:16 UTC, ezhivitsa commented
@anorsich Please, review the latest commit

2018-09-25 11:29 UTC, anorsich approved these changes

2018-09-25 11:29 UTC, merged